# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 12:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
