# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import podcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='date_broadcast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='file',
            field=models.FileField(default='b', upload_to=podcast.models.podcast_directory_path, verbose_name='Audio File'),
            preserve_default=False,
        ),
    ]
