# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20160808_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='date_broadcast',
            field=models.DateField(null=True),
        ),
    ]
