# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date_broadcast',
            field=models.DateTimeField(null=True),
        ),
    ]
