# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 10:13
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_podcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'Podcast Settings', 'verbose_name_plural': 'Podcast Settings'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Audio'),
        ),
    ]
