# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 12:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20160921_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
